"""루트 config.py를 재수출하는 shim — from shared.config import ... 호환 유지"""
import sys
from pathlib import Path

_root = Path(__file__).parent.parent.parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from config import *  # noqa: F401, F403
from config import (  # noqa: F401 (명시적 재수출)
    LLM_URL, LLM_API_KEY, LLM_MODEL, VLM_MODEL, OCR_MODEL,
    EMBEDDING_URL, EMBEDDING_MODEL, EMBEDDING_DIM,
    OPENSEARCH_HOST, OPENSEARCH_PORT, OPENSEARCH_SSL, OPENSEARCH_VERIFY_CERTS,
    OPENSEARCH_USER, OPENSEARCH_PASSWORD,
    IDX_DOCUMENTS, IDX_CHUNKS,
    POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD,
    MINIO_ENDPOINT, MINIO_ACCESS_KEY, MINIO_SECRET_KEY, MINIO_BUCKET, MINIO_SECURE,
    SERPER_URL, SERPER_API_KEY,
    UPLOAD_DIR,
    MAX_TOKENS, MIN_TOKENS,
    DOMAIN_TYPE_PATH, DOCUMENT_TYPE_PATH,
    DOMAIN_TAXONOMY, DOCUMENT_TAXONOMY,
    DOMAIN_CATEGORIES, DOCUMENT_SUBCATEGORIES,
)
